### PR TITLE
Small usability fixes

### PR DESCRIPTION
**Pull request by chapmanb**
Anurag and Yannick;
Thank you for OSwitch, this is a really brilliant contribution. I played around with this some and really loved it. I found a couple of minor things, in this small patch:
- Only try and mount directories, skipping files found in base directories
- Avoid blue text for messages which is unreadable on black background terminals

Thank you again.

### CODE REVIEW

**Comment by yeban** [comment]
I'm wondering if highlighting the text in bold would work on all kind of terminals ... or perhaps '####' before and after the message is enough?

**Comment by chapmanb** [comment]
Anurag;
From my side the message was clear enough without additional emphasis but totally your call here. Thanks again for all your work on this.

**Comment by yeban** [comment]
Thanks for the patch and the kind words, @chapmanb.

@yannickwurm I want a second opinion on whether to emphasise (if yes, how? bold?) or not - I'm leaning in favor of no emphasis.

**Comment by yannickwurm** [comment]
Hey @chapmanb - glad you like oswitch, sorry about blue on blue & thanks for the PR. 

For experienced users who understand switch/docker/etc emphasis is largely unnecessary. But naive users need some help to help determine the difference between what they can ignore and what they should at least glance at. Non-expert users is also where oswitch can add the most value. 
 With that in mind I feel we should maintain some emphasising. **bold** may indeed be most portable. Did you have a look at what commands the `brew` guys use? some of their stuff is emphasised & I suppose it is done in a portable way...

**Pull request merged**
